### ISSUE TITLE
Does the changed data gets recorded?

### ISSUE THREAD

**Issue by guettli** [jasonk/postgresql-versioning#1]
I read the readme and don't get what happens to the changed data.

I see that you store time-stamps, but I understand where the changes of the data gets changed.

Maybe I was blind ... or recording the changes to the data is not part of your project.

**Comment by jasonk** [comment]
All this does is keep a version number and timestamp to make it quick and easy to figure out which tables have changed, it doesn't do anything with the data that was changed, it still gets changed in the database.

**Comment by guettli** [comment]
Thank you for these details.
